### ISSUE TITLE
make test error

### ISSUE THREAD

**Issue by SC-Duan** [DecodeGenetics/graphtyper-pipelines#4]
Hi,
I got an error when test the pipelines  typing "make test",  so ask your help. the "graphtyper" should be  installed correctly.
the error information:
[D[E:bcf_synced_reader.h:108 operator()] alleles not defined in VCF record.
parallel: This job failed:
bash /tmp/graphtyper_calling.7IY8aM/call_script.sh /tmp/graphtyper_calling.7IY8aM/config.sh /tmp/graphtyper_calling.7IY8aM/local_bamlist 20:5000
make: *** [test] Error 1

**Comment by hannespetur** [comment]
Hello,

Looks like this is the same issue as #3. The problem comes up when using some of the recent versions of `vt`. Downgrading to `vt` git hash `6686b5c` fixed it for me.

All the best,
Hannes

**Comment by SC-Duan** [comment]
Thank you.

**Comment by hannespetur** [comment]
You're welcome.
